# This file is part of JSC's public easybuild repository (https://github.com/easybuilders/jsc)
##
# Copyright 2009-2025 Ghent University
#
# This file is part of EasyBuild,
# originally created by the HPC team of Ghent University (http://ugent.be/hpc/en),
# with support of Ghent University (http://ugent.be/hpc),
# the Flemish Supercomputer Centre (VSC) (https://www.vscentrum.be),
# Flemish Research Foundation (FWO) (http://www.fwo.be/en)
# and the Department of Economy, Science and Innovation (EWI) (http://www.ewi-vlaanderen.be/en).
#
# https://github.com/easybuilders/easybuild
#
# EasyBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation v2.
#
# EasyBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EasyBuild.  If not, see <http://www.gnu.org/licenses/>.
##
"""
EasyBuild support for building and installing CP2K, implemented as an easyblock

@author: Stijn De Weirdt (Ghent University)
@author: Dries Verdegem (Ghent University)
@author: Kenneth Hoste (Ghent University)
@author: Pieter De Baets (Ghent University)
@author: Jens Timmerman (Ghent University)
@author: Ward Poelmans (Ghent University)
@author: Luca Marsella (CSCS)
@author: Damian Alvarez (Forschungszentrum Juelich GmbH)
@author: Alan O'Cais (Forschungszentrum Juelich GmbH)
@author: Balazs Hajgato (Free University Brussels (VUB))
"""

import fileinput
import glob
import re
import os
import sys
from easybuild.tools import LooseVersion

import easybuild.tools.toolchain as toolchain
from easybuild.framework.easyblock import EasyBlock
from easybuild.framework.easyconfig import CUSTOM
from easybuild.tools.build_log import EasyBuildError
from easybuild.tools.environment import setvar
from easybuild.tools.filetools import change_dir, copy_dir, copy_file, mkdir, write_file
from easybuild.tools.config import build_option
from easybuild.tools.modules import get_software_root, get_software_version
from easybuild.tools.run import run_shell_cmd
from easybuild.tools.systemtools import get_avail_core_count


class EB_CP2K(EasyBlock):
    """
    Support for building CP2K
    - prepare module include files if required
    - generate custom config file in 'arch' directory
    - build CP2K
    - run regression test if desired
    - install by copying binary executables
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.typearch = None

        # this should be set to False for old versions of GCC (e.g. v4.1)
        self.compilerISO_C_BINDING = True

        # compiler options that need to be set in Makefile
        self.debug = ''
        self.fpic = ''

        # used for both libsmm and libxsmm
        self.libsmm = ''
        self.modincpath = ''
        self.openmp = ''

        self.make_instructions = ''

    @staticmethod
    def extra_options():
        extra_vars = {
            'extracflags': ['', "Extra CFLAGS to be added", CUSTOM],
            'extradflags': ['', "Extra DFLAGS to be added", CUSTOM],
            'ignore_regtest_fails': [False, ("Ignore failures in regression test "
                                             "(should be used with care)"), CUSTOM],
            'library': [False, "Also build CP2K as a library", CUSTOM],
            'maxtasks': [4, ("Maximum number of CP2K instances run at "
                             "the same time during testing"), CUSTOM],
            'runtest': [False, "Build and run CP2K tests", CUSTOM],
            'omp_num_threads': [None, "Value to set $OMP_NUM_THREADS to during testing", CUSTOM],
            'cuda': [False, "Enforce CUDA ", CUSTOM],
            'type': ['popt', "Type of build ('popt' or 'psmp')", CUSTOM],
            'typeopt': [True, "Enable optimization", CUSTOM],
        }
        return EasyBlock.extra_options(extra_vars)

    def _generate_makefile(self, options):
        """Generate Makefile based on options dictionary and optional make instructions"""

        text = "# Makefile generated by CP2K easyblock in EasyBuild\n"
        for key, value in sorted(options.items()):
            text += "%s = %s\n" % (key, value)
        return text + self.make_instructions

    def configure_step(self):
        """Configure build
#       - build Libint wrapper
        - generate Makefile
        """

        known_types = ['popt', 'psmp']
        if self.cfg['type'] not in known_types:
            raise EasyBuildError("Unknown build type specified: '%s', known types are %s",
                                 self.cfg['type'], known_types)

        # correct start dir, if needed
        # recent CP2K versions have a 'cp2k' dir in the unpacked 'cp2k' dir
        cp2k_path = os.path.join(self.cfg['start_dir'], 'cp2k')
        if os.path.exists(cp2k_path):
            self.cfg['start_dir'] = cp2k_path
            self.log.info("Corrected start_dir to %s" % self.cfg['start_dir'])

        # set compilers options according to toolchain config
        # full debug: -g -traceback -check all -fp-stack-check
        # -g links to mpi debug libs
        # report on extra flags being used
        if self.cfg['extracflags']:
            self.log.info("Using extra CFLAGS: %s" % self.cfg['extracflags'])
        if self.cfg['extradflags']:
            self.log.info("Using extra DFLAGS: %s" % self.cfg['extradflags'])
#            
# libsmm is mostly useless
        # lib(x)smm support
#       libsmm = get_software_root('libsmm')
        libxsmm = get_software_root('libxsmm')
        if libxsmm:
            self.cfg.update('extradflags', '-D__LIBXSMM')
            self.libsmm = '-lxsmm -lxsmmf'
            self.log.debug('Using libxsmm %s' % libxsmm)


        # set typearch   Linux-x86_64-foss.psmp/popt 
        self.typearch = "Linux-x86_64-%s" %(self.toolchain.name)
        self.log.debug(' archfile: %s.%s)' % (self.typearch,self.cfg['type']))

        # compiler toolchain specific configuration
        comp_fam = self.toolchain.comp_family()
        if comp_fam == toolchain.INTELCOMP:
            options = self.configure_intel_based()
        elif comp_fam == toolchain.GCC:
            options = self.configure_GCC_based()
        else:
            raise EasyBuildError("Don't know how to tweak configuration for compiler family %s" % comp_fam)

        # CUDA
        if self.cfg['cuda']:
            cuda = get_software_root('CUDA')
            if cuda:
                 options['DFLAGS'] += ' -D__ACC -D__DBCSR_ACC'
                 options['LIBS'] += ' -lcudart -lcublas -lcufft -lrt'
                 options['NVCC'] = ' nvcc'

        # avoid group nesting
        options['LIBS'] = options['LIBS'].replace('-Wl,--start-group', '').replace('-Wl,--end-group', '')

        options['LIBS'] = "-Wl,--start-group %s -Wl,--end-group" % options['LIBS']

        # specify correct location for 'data' directory in final installation
        options['DATA_DIR'] = os.path.join(self.installdir, 'data')

        # create arch file using options set
        archfile = os.path.join(self.cfg['start_dir'], 'arch', '%s.%s' % (self.typearch,self.cfg['type']))
        txt = self._generate_makefile(options)
        write_file(archfile, txt)
        self.log.info("Content of makefile (%s):\n%s" % (archfile, txt))

    def configure_optional(self, options):
        """configuration  of optional components """

        plumed = get_software_root('PLUMED')
        if plumed:
            options['DFLAGS'] += ' -D__PLUMED2 '
            # plumed/lib already contained in LDPATH 
            # plumed/include already contained in CPPFLAGS
            # options['LIBS'] += '-L%s/lib -lplumed -lplumedKernel ' % plumed
            options['LIBS'] += ' -lplumed -lplumedKernel ' 
            
        elpa = get_software_root('ELPA')
        if elpa:
            options['DFLAGS'] += ' -D__ELPA '
            elpaver = get_software_version('ELPA')
            # elpa/include contained in CPPFLAGS 
            # elpa/lib  contained in LDPATH
            options['ELPA_INC'] = ' -I%s/include/elpa_openmp-%s/elpa ' % (elpa,elpaver) 
            options['ELPA_INC'] += ' -I%s/include/elpa_openmp-%s/modules ' % (elpa,elpaver) 
            options['CFLAGS'] += ' $(ELPA_INC) ' 
            options['FINCLUDE'] += ' $(ELPA_INC) ' 
            options['LIBS'] += ' -lelpa_openmp ' 

        libvori = get_software_root('LIBVORI')
        if libvori:
            options['DFLAGS'] += ' -D__LIBVORI '
            options['LIBS'] += ' %s/lib/libvori.a ' % libvori 

        libxc = get_software_root('LIBXC')
        if libxc:
            options['DFLAGS'] += ' -D__LIBXC '
            #libxc/lib alread in LDPATH
            #libxc/include already in CPPFLAGS
            options['LIBS'] += ' -lxcf03 -lxc ' 

        libint = get_software_root('LIBINT')
        if libint:
            options['DFLAGS'] += ' -D__LIBINT '
            #libint/lib alread in LDPATH
            #libint/include already in CPPFLAGS
            options['LIBS'] += ' -lint2 '

        libspglib = get_software_root('SPGLIB')
        if libspglib:
            options['DFLAGS'] += ' -D__SPGLIB '
            #libspglib/lib alread in LDPATH
            #libsbplib/include already in CPPFLAGS
            options['LIBS'] += ' -lsymspg ' 
        
        libxsmm = get_software_root('LIBXSMM')
        if libxsmm:
            options['DFLAGS'] += ' -D__LIBXSMM '
            #libxsmm/lib alread in LDPATH
            #libxsmm/include already in CPPFLAGS
            options['LIBS'] += ' -lxsmmf -lxsmmext -lxsmm ' 
        
        libsmeagol = get_software_root('LIBSMEAGOL')
        if libsmeagol:
            options['DFLAGS'] += ' -D__SMEAGOL '
            #libsmeagol/lib alread in LDPATH
            #libsmeagoll/include already in CPPFLAGS
            options['LIBS'] += ' %s/lib/libsmeagol.a ' % libsmeagol  

        libfftw = get_software_root('FFTW')
        libfftwmpi = get_software_root('FFTW.MPI')
        if libfftw and libfftwmpi:
            options['DFLAGS'] += ' -D__FFTW3 '
            # lib/include already included in LDPATH, CPPFLAGS
            options['LIBS'] += ' -lfftw3_mpi -lfftw3_omp -lfftw3 '

        libdftd4 = get_software_root('DFTD4') 
        if libdftd4:
            options['DFLAGS'] += ' -D__DFTD4 '
            options['LIBS'] += ' %s/lib/libdftd4.a %s/lib/libmstore.a %s/lib/libmulticharge.a %s/lib/libmctc-lib.a ' % (libdftd4, libdftd4, libdftd4, libdftd4)  
            options['CFLAGS'] += ' -I%s/include/dftd4/GNU-14.3.0/ -I%s/include ' % (libdftd4, libdftd4) 
            options['FINCLUDE'] += ' -I%s/include/dftd4/GNU-14.3.0/ -I%s/include ' % (libdftd4, libdftd4)

        return options

    def configure_intel_based(self):
        """Configure for intel based toolchains"""
        cppflags = os.getenv('CPPFLAGS')
        ldflags = os.getenv('LDFLAGS')
        cflags = os.getenv('CFLAGS')
        cxxflags = os.getenv('CXXFLAGS')
        fflags = os.getenv('FFLAGS')
        fflags_lowopt = re.sub('-O[0-9]', '-O1', fflags)
        options = {
            'FCFLAGSGEN': '-traceback -free -fpp -fpscomp logicals ',
            'FCFLAGS': '$(FCFLAGSOPT) $(FCFLAGSGEN) $(CFLAGSOPT) $(DFLAGS) $(FINCLUDE) ',
            'FCFLAGS2': '$(FCFLAGSOPT2) $(FCFLAGSGEN) $(DFLAGS) $(FINCLUDE)  ',
            'FINCLUDE': ' %s ' % cppflags,
            'FREE': '-ffree-form -ffree-line-length-none',

            'DFLAGS': ' -D__parallel -D__SCALAPACK -D__MAX_CNTR=3  %s' % self.cfg['extradflags'],
            'CFLAGSOPT': '-fp-model precise -funroll-loops  -qopenmp-simd  ',  # -qopenmp -O2 -xHost already in cflags
            'CFLAGS': ' %s $(DFLAGS) %s  %s $(DEBUG) $(CFLAGSOPT) -std=c14 ' % (cflags, cppflags, self.cfg['extracflags']),
            'CXXFLAGS': ' %s $(DFLAGS) %s  %s  $(DEBUG) $(CFLAGSOPT) -std=c++14 ' % (cxxflags, cppflags, self.cfg['extracflags']),

            'LIBS': '',
            'AR': ' ar -r ',

            'FCFLAGSNOOPT': '$(DFLAGS) $(CFLAGS) $(FREE) -O0  $(DEBUG)',
            'FCFLAGSOPT': '%s $(FREE)  $(DEBUG)' % fflags,
            'FCFLAGSOPT2': '%s $(FREE) $(DEBUG)' % fflags_lowopt,
            'LD': ' $(FC) ',
            'LDFLAGS': ' %s ' % ldflags,
            'LDFLAGS_C': ' -nofor-main '
        }

#       in case flexiblas, mkl is default ==> -D__MKL 
#                                             MKL_LIB = $(MKLROOT)/lib/intel64
#                                             -I$(MKLROOT)/include -I$(MKLROOT)/include/fftw
        options = self.configure_optional(options)
        libxsmm = get_software_root('LIBXSMM')
        if libxsmm:
            options['LIBS'] += ' -lscalapack -L$(MKLROOT)/lib -lmkl_intel_lp64 -lmkl_sequential -lmkl_core  -lstdc++ -liomp5 '
        else: 
            options['LIBS'] += ' $(LIBSCALAPACK)  -lstdc++ -liomp5 ' 

        self.make_instructions += "mp2_optimize_ri_basis.o: mp2_optimize_ri_basis.F\n" \
               "\t$(FC) -c $(subst O2,O0,$(FCFLAGS)) $<\n"
        self.make_instructions += "paw_basis_types.o: paw_basis_types.F\n" \
               "\t$(FC) -c $(subst O2,O1,$(FCFLAGS)) $<\n"
        self.make_instructions += "mp2_ri_gpw.o: mp2_ri_gpw.F\n" \
               "\t$(FC) -c $(subst O2,O1,$(FCFLAGS)) $<\n"
        self.make_instructions += "hfx_contraction_methods.o: hfx_contraction_methods.F\n" \
               "\t$(FC) -c $(subst O2,O1,$(FCFLAGS)) $<\n"
        self.make_instructions += "commutator_rpnl.o: commutator_rpnl.F\n" \
               "\t$(FC) -c $(subst O2,O1,$(FCFLAGS)) $<\n"

        return options

    def configure_GCC_based(self):
        """Configure for GCC based toolchains"""
        cppflags = os.getenv('CPPFLAGS')
        ldflags = os.getenv('LDFLAGS')
        cflags = os.getenv('CFLAGS')
        cxxflags = os.getenv('CXXFLAGS')
        fflags = os.getenv('FFLAGS')
        fflags_lowopt = re.sub('-O[0-9]', '-O1', fflags)
        options = {
            'FCFLAGSGEN': '-fbacktrace  -fno-omit-frame-pointer -std=f2008 -fallow-argument-mismatch ',
            'FCFLAGS': '$(FCFLAGSOPT) $(FCFLAGSGEN) $(CFLAGSOPT) $(DFLAGS) $(FINCLUDE) ',
            'FCFLAGS2': '$(FCFLAGSOPT2) $(FCFLAGSGEN) $(DFLAGS) $(FINCLUDE)  ',
            'FINCLUDE': ' %s ' % cppflags,
            'FREE': '-ffree-form -ffree-line-length-none',

            'DFLAGS': ' -D__parallel -D__MPI_F08 -D__HAS_IEEE_EXCEPTIONS -D__MAX_CNTR=3  %s' % self.cfg['extradflags'],
            'CFLAGSOPT': ' -fopenmp-simd -ftree-vectorize -funroll-loops ',  # -fopenmp -O2 already in cflags
            'CFLAGS': ' %s $(DFLAGS) %s  %s $(DEBUG) $(CFLAGSOPT) -std=c17 ' % (cflags, cppflags, self.cfg['extracflags']),
            'CXXFLAGS': ' %s $(DFLAGS) %s  %s  $(DEBUG) $(CFLAGSOPT) -std=c++17 ' % (cxxflags, cppflags, self.cfg['extracflags']),

            'LIBS': '', 
            'AR': ' ar -r ',

            'FCFLAGSNOOPT': '$(DFLAGS) $(CFLAGS) $(FREE) -O0  $(DEBUG)',
            'FCFLAGSOPT': '%s $(FREE)  $(DEBUG)' % fflags,
            'FCFLAGSOPT2': '%s $(FREE) $(DEBUG)' % fflags_lowopt,
            'LD': ' $(FC) ',
            'LDFLAGS': ' %s ' % ldflags
        }
        options = self.configure_optional(options)
        libxsmm = get_software_root('LIBXSMM')
        if libxsmm:
            options['LIBS'] += ' -lscalapack -L$(MKLROOT)/lib -lmkl_gf_lp64 -lmkl_sequential -lmkl_core  -lstdc++ -lgomp '
        else: 
            options['LIBS'] += ' $(LIBSCALAPACK)  -lstdc++ -lgomp ' 

        return options


    def build_step(self):
        """Start the actual build
        - go into makefiles dir
        - patch Makefile
        -build_and_install
        """

        # update make options with MAKE
        self.cfg.update('buildopts', f'MAKE="make -j {self.cfg.parallel}"')

        # update make options with ARCH and VERSION
        self.cfg.update('buildopts', 'ARCH=%s VERSION=%s' % (self.typearch, self.cfg['type']))

        cmd = "make %s" % self.cfg['buildopts']

        # clean first
        run_shell_cmd(cmd + " clean")

        # build and install
        # compile regularly first with the default make target
        # and only then build the library
        run_shell_cmd(cmd + ' all')

        # build as a library
        if self.cfg['library']:
            run_shell_cmd(cmd + 'libcp2k')

    def test_step(self):
        """Run regression test."""

        if self.cfg['runtest']:
            if self.cfg['runtest']:
                raise EasyBuildError("test_step must be run separately on a compute node" +
                                 "jobscript template in $EBROOTCP2K/tests/jobregtesting.sh" , -9)

    def install_step(self):
        """Install built CP2K
        - copy from exe to bin
        - copy data dir (if exists)
        - copy tests
        """

        # copy executables
        exedir = os.path.join(self.cfg['start_dir'], 'exe', self.typearch)
        targetdir = os.path.join(self.installdir, 'bin')
        copy_dir(exedir, targetdir)

        # copy libraries and include files, not sure what is strictly required so we take everything
        if self.cfg['library']:
            libdir = os.path.join(self.cfg['start_dir'], 'lib', self.typearch, self.cfg['type'])
            targetdir = os.path.join(self.installdir, 'lib')
            copy_dir(libdir, targetdir)
            # Also need to populate the include directory
            targetdir = os.path.join(self.installdir, 'include')
            libcp2k_header = os.path.join(self.cfg['start_dir'], 'src', 'start', 'libcp2k.h')
            target_header = os.path.join(targetdir, os.path.basename(libcp2k_header))
            copy_file(libcp2k_header, target_header)
            # include all .mod files for fortran users (don't know the exact list so take everything)
            mod_path = os.path.join(self.cfg['start_dir'], 'obj', self.typearch, self.cfg['type'])
            for mod_file in glob.glob(os.path.join(mod_path, '*.mod')):
                target_mod = os.path.join(targetdir, os.path.basename(mod_file))
                copy_file(mod_file, target_mod)

        # copy data dir
        datadir = os.path.join(self.cfg['start_dir'], 'data')
        targetdir = os.path.join(self.installdir, 'data')
        if os.path.exists(targetdir):
            self.log.info("Won't copy data dir. Destination directory %s already exists" % targetdir)
        elif os.path.exists(datadir):
            copy_dir(datadir, targetdir)
        else:
            self.log.info("Won't copy data dir. Source directory %s does not exist" % datadir)

    def make_module_extra(self):
        """Set up a CP2K_DATA_DIR environment variable to find CP2K provided basis sets"""

        txt = super().make_module_extra()

        # also define $CP2K_DATA_DIR in module,
        # even though CP2K was already configured to pick up 'data' from install dir
        # this could be useful for users to access the 'data' dir in a documented way (and it doesn't hurt)
        datadir = os.path.join(self.installdir, 'data')
        if os.path.exists(datadir):
            txt += self.module_generator.set_environment('CP2K_DATA_DIR', datadir)

        return txt
